// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCore
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/_ViewImports.cshtml"
using PurchaSaler;

#line default
#line hidden
#line 2 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/_ViewImports.cshtml"
using PurchaSaler.Models;

#line default
#line hidden
#line 1 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
using Microsoft.AspNetCore.Identity;

#line default
#line hidden
    public class Views_Shared__LoginPartial : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
#line 2 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
SignInManager<IdentityUser> __typeHelper = default(SignInManager<IdentityUser>);

#line default
#line hidden
        }
        ))();
        ((System.Action)(() => {
#line 2 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
global::System.Object SignInManager = null;

#line default
#line hidden
        }
        ))();
        ((System.Action)(() => {
#line 3 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
UserManager<IdentityUser> __typeHelper = default(UserManager<IdentityUser>);

#line default
#line hidden
        }
        ))();
        ((System.Action)(() => {
#line 3 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
global::System.Object UserManager = null;

#line default
#line hidden
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 6 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
 if (SignInManager.IsSignedIn(User))
{
    

#line default
#line hidden
#line 9 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
                                                                                    __o = User.Identity.Name;

#line default
#line hidden
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = "Account";
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = "Manage";
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#line 10 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
         
    

#line default
#line hidden
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Controller = "Account";
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Action = "Logout";
#line 12 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
                                                                                                __o = Url.Action("Index", "Home");

#line default
#line hidden
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.RouteValues["returnUrl"] = string.Empty;
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#line 15 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
         
}
else
{
    

#line default
#line hidden
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = "Account";
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = "Register";
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#line 21 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
         
    

#line default
#line hidden
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = "Account";
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = "Login";
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
#line 24 "/home/ulquiola/WorkSpace/PurchaSaler-Asp.Net-Core-2.2/PurchaSaler/Views/Shared/_LoginPartial.cshtml"
         
}

#line default
#line hidden
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public UserManager<IdentityUser> UserManager { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public SignInManager<IdentityUser> SignInManager { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591

// 1