// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaSaler.Models;

namespace PurchaSaler.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PurchaSaler.Models.Good", b =>
                {
                    b.Property<int>("GoodID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Amount");

                    b.Property<int?>("CategoryID");

                    b.Property<string>("GoodDescribe");

                    b.Property<string>("GoodPhoto");

                    b.Property<string>("GoodTitle");

                    b.Property<decimal?>("Price");

                    b.Property<string>("Quality");

                    b.Property<int?>("ShopID");

                    b.HasKey("GoodID");

                    b.ToTable("Good");
                });
#pragma warning restore 612, 618
        }
    }
}
